apiVersion: v1
kind: Service
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  type: ClusterIP  # padrão, acessível apenas dentro do cluster
  selector:
    app: monitor
  ports:
    - protocol: TCP
      port: 3000       # porta do serviço dentro do cluster
      targetPort: 3000 # porta do container
