name: CD - Deploy to Minikube

on:
  workflow_run:
    workflows: ["CI - Build & Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image tags from CI
        uses: actions/download-artifact@v3
        with:
          name: image-tags

      - name: Start Minikube
        shell: pwsh
        run: |
          minikube start --driver=docker
          kubectl get nodes

      - name: Load Docker image into Minikube
        shell: pwsh
        run: |
          docker pull $env:IMAGE:$env:TAG_SHA
          minikube image load $env:IMAGE:$env:TAG_SHA

      - name: Deploy app to Minikube
        shell: pwsh
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout status deployment/my-app
