name: CD - Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker"]
    types: ["completed"]

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image info artifact
        uses: actions/download-artifact@v4
        with:
          name: image-info
          path: ./artifact

      - name: Load image vars
        id: vars
        run: |
          $data = Get-Content ./artifact/image-info.txt | ForEach-Object {
            $parts = $_ -split "="
            Set-Content -Path env:\$($parts[0]) -Value $parts[1]
          }
          Write-Host "Imagem: $env:IMAGE"
          Write-Host "Tag: $env:TAG_SHA"

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          $kubeDir = Join-Path $env:USERPROFILE ".kube"
          [System.IO.Directory]::CreateDirectory($kubeDir) | Out-Null
          $configPath = Join-Path $kubeDir "config"
          $raw = "${{ secrets.KUBE_CONFIG_DATA }}"
          try {
            $bytes = [System.Convert]::FromBase64String($raw)
            [System.IO.File]::WriteAllBytes($configPath, $bytes)
          } catch {
            Set-Content -Path $configPath -Value $raw -Force
          }
          "KUBECONFIG=$configPath" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Apply manifests
        run: |
          kubectl apply -f k8s/

      - name: Update app image
        run: |
          kubectl set image deployment/monitor monitor=$env:IMAGE:$env:TAG_SHA

      - name: Wait rollout
        run: kubectl rollout status deployment/monitor --timeout=120s

      - name: Show resources
        run: |
          kubectl get svc
          kubectl get pods -o wide
